---
abstract: 'SMS gateway for clicksend.com'
author:
  - 'Fayland Lam <fayland@gmail.com>'
build_requires:
  Test::More: '0.96'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.8, Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: SMS-ClickSend
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  JSON: '0'
  LWP::UserAgent: '0'
  MIME::Base64: '0'
  perl: '5.008005'
resources:
  bugtracker: https://github.com/fayland/perl-SMS-ClickSend/issues
  homepage: https://github.com/fayland/perl-SMS-ClickSend
  repository: https://github.com/fayland/perl-SMS-ClickSend.git
version: '0.01'
